version: "3.4"

services:

  web:
    image: stevymonkam/contratti-image:1.0
    ports:
      - 5008:80
    networks:
      - testcontratti
    deploy:
      replicas: 5
      placement:
        constraints:
          - "node.role==worker"
networks:
  testcontratti:
  
